### ISSUE TITLE
JBrowse as a Visualization Plugin

### ISSUE THREAD

**Issue by ashvark** [galaxyproject/hack-the-galaxy-gcc2017#26]
JBrowse is currently available as tool in galaxy toolshed. I am trying to create a Visualization plugin for JBrowse by utilising the features provided by this tool. 

 **Features:** 
- Add/Remove tracks
- Bookmark
- Saving Visualization

**Tasks and Progress:** 
- [x] Simple JBrowse Visualization plugin with sample data.
- [x] 'Save' feature of Visualization.
- [ ] Javascript methods to submit jobs of existing JBrowse tool for the data processing and store the metadata in the visualization config (In progress).
- [ ] Tracks and Bookmarks management .
